// utils/componentLabels.js (you can extract this into a separate file)
const componentDefinitions = [
  // --- Simple arrays ---
  { key: "acCooling", label: "AC Cooling" },
  { key: "heater", label: "Heater" },
  { key: "climateControlAc", label: "Climate Control AC" },
  { key: "steering", label: "Steering" },
  { key: "suspension", label: "Suspension" },
  { key: "brake", label: "Brake" },

  // --- Categories ---
  { key: "powerWindowsLhsFront", label: "LHS Front Power Window" },
  { key: "powerWindowsLhsRear", label: "LHS Rear Power Window" },
  { key: "powerWindowsRhsFront", label: "RHS Front Power Window" },
  { key: "powerWindowsRhsRear", label: "RHS Rear Power Window" },
  { key: "airbagFeature", label: "Airbag Feature" },
  { key: "abs", label: "ABS" },
  { key: "musicSystem", label: "Music System" },
  { key: "steeringMountedAudioControl", label: "Steering Mounted Audio Control" },
  { key: "leatherSeat", label: "Leather Seat" },
  { key: "fabricSeat", label: "Fabric Seat" },
  { key: "sunroof", label: "Sunroof" },
  { key: "rearDefogger", label: "Rear Defogger" },
  { key: "reverseCamera", label: "Reverse Camera" },

  // --- Engine Components ---
  { key: "battery", label: "Battery" },
  { key: "engineOilLevelDipstick", label: "Engine Oil Level Dipstick" },
  { key: "engineOil", label: "Engine Oil" },
  { key: "coolant", label: "Coolant" },
  { key: "engineMounting", label: "Engine Mounting" },
  { key: "engineSound", label: "Engine Sound" },
  { key: "exhaustSmoke", label: "Exhaust Smoke" },
  { key: "turboCharger", label: "Turbo Charger" },
  { key: "fuelInjector", label: "Fuel Injector" },
  { key: "clutch", label: "Clutch" },
  { key: "gearShifting", label: "Gear Shifting" },

  // --- Exterior (Front/Rear/Left/Right) ---
  { key: "frontWindshield", label: "Front Windshield" },
  { key: "frontBumper", label: "Front Bumper" },
  { key: "bonnetHood", label: "Bonnet/Hood" },
  { key: "lhsHeadlight", label: "Head Light" },
  { key: "lhsFogLight", label: "Fog Light" },
  { key: "lhsApronLeg", label: "LHS Apron Leg" },
  { key: "rhsApronLeg", label: "RHS Apron Leg" },
  { key: "grill", label: "Grill" },
  { key: "firewall", label: "Firewall" },
  { key: "cowlTop", label: "Cowl Top" },
  { key: "lowerCrossMember", label: "Lower Cross Member" },
  { key: "upperCrossMember", label: "Upper Cross Member" },
  { key: "headLightSupport", label: "Head Light Support" },
  { key: "radiatorSupport", label: "Radiator Support" },
  { key: "alloyWheel", label: "Alloy Wheel" },
  { key: "lhsFender", label: "LHS Fender" },
  { key: "lhsTyre", label: "LHS Tyre" },
  { key: "lhsOrvm", label: "LHS ORVM" },
  { key: "lhsFrontDoor", label: "LHS Front Door" },
  { key: "lhsRearDoor", label: "LHS Rear Door" },
  { key: "lhsPillarA", label: "LHS Pillar A" },
  { key: "lhsPillarB", label: "LHS Pillar B" },
  { key: "lhsPillarC", label: "LHS Pillar C" },
  { key: "lhsRunningBorder", label: "LHS Running Border" },
  { key: "lhsQuarterPanel", label: "LHS Quarter Panel" },
  { key: "rearWindshield", label: "Rear Windshield" },
  { key: "rearBumper", label: "Rear Bumper" },
  { key: "bootTrunk", label: "Boot/Trunk" },
  { key: "dickyDoor", label: "Dicky Door" },
  { key: "bootFloor", label: "Boot Floor" },
  { key: "lhsTaillight", label: "LHS Taillight" },
  { key: "rhsTaillight", label: "RHS Taillight" },
  { key: "spareTyre", label: "Spare Tyre" },
  { key: "rhsFender", label: "RHS Fender" },
  { key: "rhsTyre", label: "RHS Tyre" },
  { key: "rhsOrvm", label: "RHS ORVM" },
  { key: "rhsFrontDoor", label: "RHS Front Door" },
  { key: "rhsRearDoor", label: "RHS Rear Door" },
  { key: "rhsPillarA", label: "RHS Pillar A" },
  { key: "rhsPillarB", label: "RHS Pillar B" },
  { key: "rhsPillarC", label: "RHS Pillar C" },
  { key: "rhsRunningBorder", label: "RHS Running Border" },
  { key: "rhsQuarterPanel", label: "RHS Quarter Panel" },
  { key: "lhsAppron", label: "LHS Appron", },
  { key: "rhsAppron", label: "RHS Appron", },
  { key: "rhsHeadLight", label: "RHS Head Light" },
  { key: "leftRearTyre", label: "Left Rear Tyre",  },
  { key: "rightRearTyre", label: "Right Rear Tyre",},
   { key: "leftFrontTyre", label: "Left Front Tyre",  },
  { key: "rightFrontTyre", label: "Right Front Tyre",},
   { key: "front", label: "Front", type: "image" },
            { key: "left", label: "Left", type: "image" },
           { key: "rear", label: "Rear", type: "image" },
          { key: "right", label: "Right", type: "image" },

];

// Build a lookup map
export const componentLabelMap = componentDefinitions.reduce((map, comp) => {
  map[comp.key] = comp.label;
  return map;
}, {});
